import Image from 'next/image';
import { Reveal } from '@/components/reveal';
import { SmoothScroll } from '@/components/smooth-scroll';
import { ThemeToggle } from '@/components/theme-toggle';

const chapters = [
  { number: '01', title: 'Foundation', body: <>I started a B.Sc. in Computer Science at Air University, Islamabad in Fall 2025. Before that, I taught myself the frontend fundamentals that make a product interface dependable: HTML5, CSS3, Tailwind CSS, JavaScript and TypeScript, REST APIs, UI/UX, Git, and CI/CD.</> },
  { number: '02', title: 'Practical experience', body: <>From July through August 2026, I completed FlyRank’s Front-end AI Engineering internship. It focused on AI fluency alongside applied frontend engineering—using AI tooling thoughtfully while keeping the product experience, implementation, and engineering choices clear.</> },
  { number: '03', title: 'What I’ve shipped', body: <>I’ve built four self-directed React production apps: ShopNest, FoodieX, NovaSaaS, and SmartHire. I also built PulseCRM, an AI-powered sales CRM with Next.js and the Vercel AI SDK. Each project is an opportunity to make state, motion, and interface hierarchy work together with a useful purpose.</> },
  { number: '04', title: 'Technical direction', body: <>My core stack is React 18, Next.js, Node.js, TypeScript, Tailwind CSS, GSAP, Framer Motion, and Zustand. I’m currently expanding into Python, Django REST, and PostgreSQL to understand and contribute across the application boundary—not only at the interface layer.</> },
  { number: '05', title: 'Where I’m headed', body: <>I’m moving toward full-stack development with Django and AI integration: building products where the frontend experience, API contract, data layer, and AI capabilities can be shaped as one coherent system.</> }
];

export default function AboutPage() {
  return <SmoothScroll><header className="section-shell sticky top-0 z-20 flex h-20 items-center justify-between gap-3 bg-paper/90 backdrop-blur dark:bg-[#101612]/90"><a href="/" className="font-display text-2xl font-semibold sm:text-3xl">Sarfraz<em className="text-clay">.</em></a><nav className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-wide sm:gap-6 sm:text-xs sm:tracking-widest" aria-label="Primary"><a href="/">Home</a><a className="text-clay" href="/about">About</a><a href="/projects">Projects</a><a href="/contact">Contact</a></nav><ThemeToggle /></header><main><section className="section-shell grid gap-12 py-20 sm:py-28 lg:grid-cols-[1.1fr_.9fr]"><Reveal><p className="eyebrow">About</p><h1 className="mt-3 max-w-3xl font-display text-6xl leading-none sm:text-8xl">A builder who likes things to make <em>sense.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-ink/70 dark:text-white/70">I’m Sarfraz Saeed, a Computer Science student and frontend engineer in Islamabad. I care about building digital products that feel composed on the surface and stay understandable underneath.</p></Reveal><Reveal className="mx-auto w-full max-w-sm"><Image src="/headshot.png" alt="Sarfraz Saeed" width={960} height={1200} className="rounded-[2rem] border border-ink/10 dark:border-white/10" priority /></Reveal></section><section className="border-y border-ink/10 bg-mist/45 py-8 dark:border-white/10 dark:bg-white/[.03]"><div className="section-shell"><p className="max-w-3xl font-display text-3xl leading-tight sm:text-4xl">The work is about more than a polished screen: it is an effort to make a product easier to understand, change, and use.</p></div></section><section className="section-shell py-24 sm:py-32"><div className="mx-auto max-w-3xl divide-y divide-ink/10 dark:divide-white/10">{chapters.map((chapter) => <Reveal key={chapter.number}><article className="grid gap-5 py-10 sm:grid-cols-[5rem_1fr]"><p className="font-display text-3xl italic text-clay">{chapter.number}</p><div><h2 className="font-display text-4xl leading-none sm:text-5xl">{chapter.title}</h2><p className="mt-5 max-w-2xl leading-8 text-ink/70 dark:text-white/70">{chapter.body}</p></div></article></Reveal>)}</div></section></main></SmoothScroll>;
}
