import Image from 'next/image';
import { Reveal } from '@/components/reveal';
import { SiteHeader } from '@/components/site-header';
import { SmoothScroll } from '@/components/smooth-scroll';

const certifications = [
  { issuer: 'Meta · Coursera', date: 'July 2026', title: 'HTML and CSS in Depth', description: 'Semantic markup, layout systems, responsive composition, and browser behavior for production interfaces.', tags: 'HTML5 · CSS3 · Responsive Layouts', image: '/certificates/cert-html-css.png', href: 'https://coursera.org/verify/4A3R4Z1O61WH' },
  { issuer: 'micro1', date: 'July 2026', title: 'React / JavaScript / ES6+ Certification', description: 'Technical assessment covering React fundamentals, modern JavaScript, ES6+ syntax, hooks, and async logic.', tags: 'React · JavaScript · ES6+', image: '/certificates/cert-micro1.png' },
  { issuer: 'Deloitte Australia · Forage', date: 'July 2026', title: 'Technology Job Simulation', description: 'A simulated technology consulting engagement covering client requirements, coded solutions, and technical recommendations.', tags: 'Consulting · Technical Proposals', image: '/certificates/cert-deloitte.png', href: 'https://www.theforage.com/completion-certificates/9PBTqmSxAf6zZTseP/udmxiyHeqYQLkTPvf_9PBTqmSxAf6zZTseP_6a4167a0806a16122e52949c_1783100224593_completion_certificate.pdf' },
  { issuer: 'Skyscanner · Forage', date: 'July 2026', title: 'Front-End Software Engineering Simulation', description: 'Simulated front-end engineering tasks including component work, debugging, and production-style code.', tags: 'JavaScript · Debugging · UI Components', image: '/certificates/cert-skyscanner.png', href: 'https://www.theforage.com/completion-certificates/skoQmxqhtgWmKv2pm/km4rw7dihDr3etqom_skoQmxqhtgWmKv2pm_6a4167a0806a16122e52949c_1782919302683_completion_certificate.pdf' },
  { issuer: 'Meta · Coursera', date: 'May 2026', title: 'Introduction to Front-End Development', description: 'Semantic HTML5, CSS3, responsive design systems, Bootstrap 5, and modern frontend workflows.', tags: 'HTML5 · CSS3 · Bootstrap 5', image: '/certificates/cert-meta.png', href: 'https://coursera.org/verify/L2A0K7DI5ZHZ' },
  { issuer: 'FlyRank AI', date: 'August 2026', title: 'Front-end AI Engineering Internship', description: 'Completed FlyRank’s internship programme focused on AI-assisted frontend engineering, technical competency, and collaborative product work.', tags: 'AI Engineering · Frontend · Collaboration', image: '/certificates/cert-flyrank.png', href: 'https://internship.flyrank.ai/verify' },
  { issuer: 'Version Control', date: '2026', title: 'Version Control with Git', description: 'A foundation in collaborative Git workflows, branching, history, and the habits that make changes reviewable.', tags: 'Git · GitHub · Collaboration', image: '/certificates/cert-version-control.png' }
];

export default function CertificationsPage() {
  return <SmoothScroll><SiteHeader active="/certifications" /><main className="section-shell py-20 sm:py-28"><Reveal><p className="eyebrow">Certifications</p><h1 className="mt-3 max-w-3xl font-display text-6xl leading-none sm:text-8xl">Credentials that support the <em>practice.</em></h1><p className="mt-7 max-w-2xl leading-8 text-ink/65 dark:text-white/65">A record of focused study, technical assessments, and simulated engineering work alongside the projects I build.</p></Reveal><div className="mt-14 grid grid-cols-2 gap-3">{certifications.map((cert, index) => <Reveal key={cert.title}><article className="overflow-hidden rounded-lg border border-ink/10 bg-white/40 dark:border-white/10 dark:bg-white/[.03]"><div className="relative aspect-[16/9] overflow-hidden bg-mist dark:bg-white/10"><Image src={cert.image} alt={`${cert.title} certificate`} fill sizes="(max-width: 768px) 50vw, 190px" className="object-contain object-center" /></div><div className="p-3"><p className="text-[8px] font-bold uppercase leading-3 tracking-[.12em] text-clay">{cert.issuer} · {cert.date}</p><h2 className="mt-2 text-sm font-extrabold leading-tight">{cert.title}</h2><p className="mt-2 text-[9px] leading-4 text-ink/65 dark:text-white/65">{cert.description}</p><p className="mt-3 text-[8px] font-bold leading-3 text-ink/55 dark:text-white/55">{cert.tags}</p>{cert.href ? <a href={cert.href} target="_blank" rel="noreferrer" className="link-underline mt-3 inline-block text-[9px] font-bold">View certificate ↗</a> : <p className="mt-3 text-[9px] font-bold text-moss dark:text-[#9bc7a4]">Completed</p>}</div></article></Reveal>)}</div></main></SmoothScroll>;
}